const $=id=>document.getElementById(id);let catalog=null;let imageData='';
const type=$('type'),template=$('template'),preview=$('preview');
const defaults={postal:{title:'San Patricio del Chañar',body:'Un fragmento de nuestro territorio.',place:'San Patricio del Chañar · Neuquén',date:''},ficha:{title:'Ficha local',body:'Descripción del lugar, persona, institución o patrimonio.',place:'San Patricio del Chañar',date:''},guia:{title:'Guía breve',body:'Una pequeña guía para conocer el territorio.',place:'San Patricio del Chañar',date:''},mapa:{title:'Mapa esquemático',body:'Referencia territorial. Verificar cada ubicación antes de publicar.',place:'San Patricio del Chañar · Neuquén',date:''}};
fetch('data.json').then(r=>r.json()).then(d=>{catalog=d;refreshTemplates();render();loadSaved()}).catch(()=>{catalog={postal:[],ficha:[],guia:[],mapa:[]};refreshTemplates();render()});
function refreshTemplates(){template.innerHTML=(catalog[type.value]||[]).map(x=>`<option value="${x.id}" data-ratio="${x.ratio}">${x.id} — ${x.name}</option>`).join('')}
type.addEventListener('change',()=>{refreshTemplates();const d=defaults[type.value];$('title').value=d.title;$('body').value=d.body;$('place').value=d.place;$('date').value=d.date;render()});[template,$('title'),$('place'),$('body'),$('date'),$('source'),$('credit')].forEach(el=>el.addEventListener('input',render));
$('image').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{imageData=reader.result;$('previewImage').src=imageData;$('previewImage').hidden=false;$('previewImage').previousElementSibling.style.display='none';render()};reader.readAsDataURL(f)});
function render(){const t=type.value;const ratio=template.selectedOptions[0]?.dataset.ratio||'landscape';preview.className=`product ${ratio}`;$('previewType').textContent=(template.selectedOptions[0]?.textContent||t).split(' — ')[1]||t.toUpperCase();$('previewTitle').textContent=$('title').value||defaults[t].title;$('previewBody').textContent=$('body').value||'';$('previewPlace').textContent=$('place').value||'';$('previewDate').textContent=$('date').value||'';$('previewCredit').textContent=$('credit').value||'Ocarina Producciones';$('previewSource').textContent=$('source').value?`Fuente: ${$('source').value}`:''}
async function imageBlob(kind='png'){const canvas=await html2canvas(preview,{scale:2,useCORS:true,backgroundColor:null});return new Promise(res=>canvas.toBlob(res,`image/${kind}`,.92))}
async function download(kind){const blob=await imageBlob(kind);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`chanar-${Date.now()}.${kind}`;a.click();URL.revokeObjectURL(a.href)}
$('png').onclick=()=>download('png');$('jpg').onclick=()=>download('jpeg');$('print').onclick=()=>window.print();
$('pdf').onclick=async()=>{const canvas=await html2canvas(preview,{scale:2,useCORS:true,backgroundColor:'#222'});const {jsPDF}=window.jspdf;const w=canvas.width,h=canvas.height;const pdf=new jsPDF({orientation:w>h?'landscape':'portrait',unit:'px',format:[w,h]});pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',0,0,w,h);pdf.save(`chanar-${Date.now()}.pdf`)};
$('generate').onclick=()=>{render();$('preview').animate([{transform:'scale(.985)'},{transform:'scale(1)'}],{duration:220})};
$('save').onclick=()=>{const item={id:crypto.randomUUID(),type:type.value,template:template.value,title:$('title').value,place:$('place').value,body:$('body').value,date:$('date').value,source:$('source').value,credit:$('credit').value,image:imageData,created:new Date().toISOString()};const arr=JSON.parse(localStorage.getItem('fabrica-chanar')||'[]');arr.unshift(item);localStorage.setItem('fabrica-chanar',JSON.stringify(arr.slice(0,30)));loadSaved()};
function loadSaved(){const arr=JSON.parse(localStorage.getItem('fabrica-chanar')||'[]');$('saved').innerHTML=arr.length?arr.map(x=>`<div class="saved-card"><strong>${esc(x.title||'Sin título')}</strong><small>${esc(x.type)} · ${new Date(x.created).toLocaleDateString('es-AR')}</small><button onclick="restore('${x.id}')">Abrir</button></div>`).join(''):'<p class="eyebrow">Todavía no guardaste productos en este navegador.</p>'}
window.restore=id=>{const x=JSON.parse(localStorage.getItem('fabrica-chanar')||'[]').find(y=>y.id===id);if(!x)return;type.value=x.type;refreshTemplates();template.value=x.template;$('title').value=x.title;$('place').value=x.place;$('body').value=x.body;$('date').value=x.date;$('source').value=x.source;$('credit').value=x.credit;imageData=x.image||'';if(imageData){$('previewImage').src=imageData;$('previewImage').hidden=false;$('previewImage').previousElementSibling.style.display='none'}render();scrollTo({top:0,behavior:'smooth'})};
$('clearBtn').onclick=()=>{['title','place','body','date','source'].forEach(id=>$(id).value='');imageData='';$('previewImage').hidden=true;$('previewImage').previousElementSibling.style.display='';render()};
$('exportLibrary').onclick=()=>{const blob=new Blob([localStorage.getItem('fabrica-chanar')||'[]'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='biblioteca-fabrica-chanar.json';a.click()};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
